### ISSUE TITLE
Data set details

### ISSUE THREAD

**Issue by davy9501** [bdecost/uhcsdb#1]
Can you please provide the corresponding process parameters of microstructure images in the data set? 
I did not find the corresponding label in the data set. Thank you!!!

**Comment by bdecost** [comment]
The processing metadata is stored in the `Sample` table, which you can access via a sqlalchemy relationship join from a `Micrograph` record.

So if you have a `Micrograph` record `m`, you can do `m.sample.anneal_temperature` to reference the annealing temperature, for example...

Also, I just added `[scripts/export_metadata.py](https://github.com/bdecost/uhcsdb/blob/master/scripts/export_metadata.py)`, which shows how to load all the metadata into a pandas dataframe. This is probably the easiest way to load the entire dataset for analysis outside of the flask app.

**Comment by davy9501** [comment]
Thank you so much!  You are so helpful, I do appreciate it.
